# Vault-injected secrets for Saaspet
# This file is generated by Vault Agent - DO NOT EDIT MANUALLY

# Database
DB_CONNECTION=pgsql
DB_HOST={{ with secret "secret/saaspet/database" }}{{ .Data.data.host }}{{ end }}
DB_PORT={{ with secret "secret/saaspet/database" }}{{ .Data.data.port }}{{ end }}
DB_DATABASE={{ with secret "secret/saaspet/database" }}{{ .Data.data.database }}{{ end }}
DB_USERNAME={{ with secret "secret/saaspet/database" }}{{ .Data.data.username }}{{ end }}
DB_PASSWORD={{ with secret "secret/saaspet/database" }}{{ .Data.data.password }}{{ end }}

# Redis
REDIS_HOST={{ with secret "secret/saaspet/redis" }}{{ .Data.data.host }}{{ end }}
REDIS_PASSWORD={{ with secret "secret/saaspet/redis" }}{{ .Data.data.password }}{{ end }}
REDIS_PORT={{ with secret "secret/saaspet/redis" }}{{ .Data.data.port }}{{ end }}

# Application
APP_KEY={{ with secret "secret/saaspet/app" }}{{ .Data.data.key }}{{ end }}
JWT_SECRET={{ with secret "secret/saaspet/jwt" }}{{ .Data.data.secret }}{{ end }}
ENCRYPTION_KEY={{ with secret "secret/saaspet/encryption" }}{{ .Data.data.key }}{{ end }}

# Stripe
STRIPE_KEY={{ with secret "secret/saaspet/stripe" }}{{ .Data.data.key }}{{ end }}
STRIPE_SECRET={{ with secret "secret/saaspet/stripe" }}{{ .Data.data.secret }}{{ end }}
STRIPE_WEBHOOK_SECRET={{ with secret "secret/saaspet/stripe" }}{{ .Data.data.webhook_secret }}{{ end }}

# Paddle
PADDLE_VENDOR_ID={{ with secret "secret/saaspet/paddle" }}{{ .Data.data.vendor_id }}{{ end }}
PADDLE_API_KEY={{ with secret "secret/saaspet/paddle" }}{{ .Data.data.api_key }}{{ end }}
PADDLE_WEBHOOK_SECRET={{ with secret "secret/saaspet/paddle" }}{{ .Data.data.webhook_secret }}{{ end }}

# Resend
RESEND_API_KEY={{ with secret "secret/saaspet/resend" }}{{ .Data.data.api_key }}{{ end }}

# Sentry
SENTRY_LARAVEL_DSN={{ with secret "secret/saaspet/sentry" }}{{ .Data.data.dsn }}{{ end }}

# MinIO / Cloudflare R2
FILESYSTEM_DISK=s3
AWS_ACCESS_KEY_ID={{ with secret "secret/saaspet/storage" }}{{ .Data.data.access_key }}{{ end }}
AWS_SECRET_ACCESS_KEY={{ with secret "secret/saaspet/storage" }}{{ .Data.data.secret_key }}{{ end }}
AWS_DEFAULT_REGION={{ with secret "secret/saaspet/storage" }}{{ .Data.data.region }}{{ end }}
AWS_BUCKET={{ with secret "secret/saaspet/storage" }}{{ .Data.data.bucket }}{{ end }}
AWS_ENDPOINT={{ with secret "secret/saaspet/storage" }}{{ .Data.data.endpoint }}{{ end }}
AWS_USE_PATH_STYLE_ENDPOINT=true

# Reverb
REVERB_APP_ID={{ with secret "secret/saaspet/reverb" }}{{ .Data.data.app_id }}{{ end }}
REVERB_APP_KEY={{ with secret "secret/saaspet/reverb" }}{{ .Data.data.app_key }}{{ end }}
REVERB_APP_SECRET={{ with secret "secret/saaspet/reverb" }}{{ .Data.data.app_secret }}{{ end }}
REVERB_HOST={{ with secret "secret/saaspet/reverb" }}{{ .Data.data.host }}{{ end }}
REVERB_PORT={{ with secret "secret/saaspet/reverb" }}{{ .Data.data.port }}{{ end }}
REVERB_SCHEME={{ with secret "secret/saaspet/reverb" }}{{ .Data.data.scheme }}{{ end }}

# Mail
MAIL_MAILER=resend
MAIL_FROM_ADDRESS={{ with secret "secret/saaspet/mail" }}{{ .Data.data.from_address }}{{ end }}
MAIL_FROM_NAME="{{ with secret "secret/saaspet/mail" }}{{ .Data.data.from_name }}{{ end }}"

# Logging
LOG_CHANNEL=stack
LOG_LEVEL=info